#!/bin/bash

[ ! -d "node_modules" ] && npm install

echo "
================================ PHP Code ===========================
"
vendor/bin/phpcs plugins --tab-width=4 -n --standard=PSR2
vendor/bin/phpmd plugins ansi phpmd.ruleset.xml
echo "
================================ Twig Code ==========================
"
vendor/bin/twigcs themes/front/templates --severity error --display blocking
echo "
================================ JS Code ============================
"
node_modules/.bin/eslint themes/front/src/js/
echo "
================================ SCSS Code ==========================
"
node_modules/.bin/stylelint themes/front/src/css/**/*.scss --custom-syntax postcss-scss