field: 646a52b6-154e-4e2e-846b-72c6d35feadf # Timer
fieldLayouts:
  d8704889-aa0a-4eb3-af33-2f50f43fb600:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0bbe1fb4-9b45-447e-93e8-1f16b25a2605 # Task
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff4b217b-7b48-4cd6-bf15-33e3c4dc2940
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3439d966-0cfa-4d4e-b23d-3b46389380f1 # Started
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31547264-6aae-4656-8de5-b91c8b4707fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c30ea898-5322-46b3-8448-e0ddb359efe6
        userCondition: null
fields:
  0bbe1fb4-9b45-447e-93e8-1f16b25a2605: # Task
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: task
    instructions: null
    name: Task
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:720dc906-57fd-4848-92a1-447acf4703f3' # Task
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  3439d966-0cfa-4d4e-b23d-3b46389380f1: # Started
    columnSuffix: ckbtvltn
    contentColumnType:
      - 'date:datetime'
      - 'tz:string'
    fieldGroup: null
    handle: started
    instructions: null
    name: Started
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 5
      showDate: true
      showTime: true
      showTimeZone: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: timer
name: Timer
sortOrder: 1
