fieldLayouts:
  003f84ae-e1bd-42a0-b829-fe0f7254d252:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a086d37e-aa74-444d-83af-da0a59c047a5
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: c4b2ede2-8d31-4a1b-b964-e30970963215
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ad55fd2-2c4e-436b-a572-d9d4bef64524 # Basic Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b6a2c40-7b12-4cd7-b260-00c76854b485
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: adf8ae8e-b988-4997-a9ad-98b06edae9cf
        userCondition: null
handle: breaks
hasTitleField: true
name: Breaks
section: d647773f-b5fa-4abf-93a9-e181c4d9d5d4 # Breaks
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
