fieldLayouts:
  d87688c1-d93b-4a7a-be8f-4347c8b57bca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c2d06c40-6ee3-456c-81cf-36694c0b9d05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79cfda90-52f0-4348-b604-fdb241c209cf # Task
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cba1b95-a56d-4cec-9185-19648a46eb08
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: beb8aabf-7970-4442-9f8b-f70568d8757a # Start date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1709408c-a1ca-450a-be53-c993f8925c99
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 285c99c4-fa78-44f1-afd3-6eed1b0d5121 # End date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5ee1978-21f3-489a-aa4c-50ac22714f2b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 517fab63-1440-4eb0-a2a1-200d160e602a
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 877c3423-006e-4942-bfdb-c44bac344c97 # Timesheet
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{{ task.one().title }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
