fieldLayouts:
  5740ce65-65cc-4b2b-ab7b-a350a3c85fc7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf75eb83-6d2b-4ce2-9f62-353bd74fe8a9
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 34016fb2-d922-4483-809c-f30801615184 # Background color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0502087-f13a-4462-afb5-df01db5dfe90
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: beb8aabf-7970-4442-9f8b-f70568d8757a # Start date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f90d6aa-c774-4617-a35f-164ba30b1dd2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a7c9164e-c77f-412f-8498-26092f7a0289 # Deadline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 558c739a-5abc-4652-ba78-81ed443a3bb1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a25335f0-9a1f-4a5a-bb1b-f3d4480f55b1 # Committed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c4d1747-6291-410c-a193-2131f3cce266
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 980e2254-b65d-438b-b268-bc4a24184302 # Order
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3387d13-058c-480f-be0c-326a605add24
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8c7680f9-dce8-43c7-b972-8c7b47508cb3 # Paused
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e4144cc-dbda-4cc0-8367-a6ff606a6416
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a8096a2c-fe5e-4bee-8e2d-2fdd17c42bb5 # Recurring
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89a5af8f-3c8c-4ee6-aca7-3106086ab495
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 75f26b47-fb20-47e9-9ad1-bab31babae60 # Time based
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dda8e09e-c90a-4a46-ae5a-45f61056d5d3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a8096a2c-fe5e-4bee-8e2d-2fdd17c42bb5 # Recurring
                  uid: 8841255d-ffd4-4fdd-bbe5-4f79e05be5b0
                  value: true
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 75f26b47-fb20-47e9-9ad1-bab31babae60 # Time based
                  uid: d57375ae-f458-4aba-8809-8c98bbf0f74c
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: ce461ea7-466c-4a18-ab4f-dddeb94af716 # Weeks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 071aa78f-5eee-4c85-a9b0-8a6b2fc9f728
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 75f26b47-fb20-47e9-9ad1-bab31babae60 # Time based
                  uid: a2cd8359-a2f8-442c-9ab5-4a69b362c601
                  value: false
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: a8096a2c-fe5e-4bee-8e2d-2fdd17c42bb5 # Recurring
                  uid: 6b5b2a2a-f7a0-4d2b-921d-669b42f97387
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: aab9913c-15e8-4209-b0b1-a72e0945aecb # Weeks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60773b37-a08a-4088-9f78-063d52df5211
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 75f26b47-fb20-47e9-9ad1-bab31babae60 # Time based
                  uid: 4b1db6ab-f3b2-4e72-96b9-7bf8dd166b7d
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1b238269-1e74-4eb1-aca9-256f0fca08b9 # Task type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 504682da-b7c2-42c7-8e00-223fa74b839e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 75f26b47-fb20-47e9-9ad1-bab31babae60 # Time based
                  uid: 31ba3dd1-5edb-4477-827e-6d3860e0eb6b
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 70279873-4261-4f79-b9d0-6dc067fb97b4 # Length
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc49c163-0107-4b9f-8f0a-f5e8eac03756
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: cbfbd016-f81d-4cb1-ad1c-c411dfae2249
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 720dc906-57fd-4848-92a1-447acf4703f3 # Task
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
