fieldLayouts:
  ec2bf51d-f213-4bd7-8ab7-688b58a384f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5208d4d-5b3b-4574-866f-21945ddf7262
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79cfda90-52f0-4348-b604-fdb241c209cf # Task
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7e4c25d-0e0d-41cc-ada4-0c0413a689ce
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: beb8aabf-7970-4442-9f8b-f70568d8757a # Start date
            instructions: null
            label: Date
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc4d7e58-14e7-4391-ae79-f11f9dc8b630
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4b8fd5c8-4aaa-4384-8956-861ce041def9 # Charge succeeded
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98445968-964f-44c1-89a4-e7ff740424c2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8ad10f9f-e461-4fb0-85a8-76ffc63cfb81 # Charge
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8c7d1b1-935a-497f-9526-9463aeef66a1
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: cfa8e91f-1379-43f1-9dda-482c386d678d
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: a375ef2c-b9ee-4506-8059-6d56c1173cbb # Derail
sortOrder: 1
titleFormat: '{{ task.one().title }} - {{ task.startDate|date(''d/m/Y'') }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
