fieldLayouts:
  16dc3c2d-ff0a-452a-9fe3-c0909e218327:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e41367a5-a80f-4c40-9a90-a7f468b0aa28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 79cfda90-52f0-4348-b604-fdb241c209cf # Task
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 017ae52f-60be-459e-bc4f-17fe7cc005db
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: beb8aabf-7970-4442-9f8b-f70568d8757a # Start date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f992b7-0bc5-4234-abb9-094519f168db
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a7c9164e-c77f-412f-8498-26092f7a0289 # Deadline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 556ea379-a45a-4bc4-80af-7e38a0483fde
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 70279873-4261-4f79-b9d0-6dc067fb97b4 # Length
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0a5b545-6d26-45a2-b170-cfe6cababbc6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d0af2316-3920-45e2-a0c7-5bf31b6f07ff # Is complete
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c7ad3db-4b38-4690-9120-1e3450e00ecf
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 09820409-0f3c-4854-953a-be99dbf26244
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 35489b9b-396d-4bf5-b052-a28c816a8095 # Scheduled task
sortOrder: 1
titleFormat: '{task.one().title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
