fieldLayouts:
  bc1b4670-b7b8-4b39-b1d4-571ae9e84bac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 40e8df1f-dfaa-404c-8f68-302970b92f59
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: ff7a45f6-249e-4401-b035-ed21eb6dd7ec # Invalid subscription message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a2c5b6b-daa5-4ecf-bf95-a305b98066ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d587d831-bd70-4f82-a9bc-68024ea75421
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ad55fd2-2c4e-436b-a572-d9d4bef64524 # Basic Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15346234-375a-4f82-ba0d-8d30845f036c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a1dc3178-e612-447a-825f-69dc718c84b1
        userCondition: null
handle: newTask
hasTitleField: true
name: 'New task'
section: bf477c2a-b2b3-4dde-a0e0-0978de99ab77 # New task
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
