fieldLayouts:
  ecb39324-e6e9-4e4f-99ac-113da781fa4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f090ec7-8eae-4818-8c3e-b6eead6ab90c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f4994683-7a71-491d-b14b-0a986b8ec613 # Requires valid subscription
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 316fea9b-c734-49cf-9ff2-3e31dd4c7af4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e4dc77ff-7c96-4d98-b434-ed37c72fa8be # Matrix Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ad613a1-e14e-4af1-852d-649f80713c8a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d563b5dd-f748-4ca1-a8cb-87ad806fb224
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ad55fd2-2c4e-436b-a572-d9d4bef64524 # Basic Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bf3f37b-8691-4262-917c-cbc796151258
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a341c66f-d718-4a45-a4f6-d04437774fdf
        userCondition: null
handle: paySubscription
hasTitleField: true
name: 'Pay subscription'
section: a260febd-af3b-4bda-ba4c-67c7a8edb8d4 # Pay subscription
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
