fieldLayouts:
  c454d1fb-a16e-420f-9f65-4df5615f20e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ca94ed0e-b550-4c6b-8b48-28b6ccc1e608
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f4994683-7a71-491d-b14b-0a986b8ec613 # Redirect to save card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a908a3-26e1-483d-8425-c171b96fac00
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e4dc77ff-7c96-4d98-b434-ed37c72fa8be # Matrix Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45be48f1-6895-4d8b-92f0-e6b20d006352
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ec7c1a0-0710-45a2-a246-efba168c60dd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ad55fd2-2c4e-436b-a572-d9d4bef64524 # Basic Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b36aa9fe-5ac4-44cc-98c3-29897a51e002
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 80b2a8de-a4e8-429a-a53b-f4ec45238540
        userCondition: null
handle: tasks
hasTitleField: true
name: Tasks
section: 754e6619-64f1-4d4d-8a61-6df6f90e5a9b # Tasks
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
