fieldLayouts:
  44db7e3c-560d-4fb3-8b01-2c0dda5fe2d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24901bc8-fe97-4c30-8e0d-d6908b915a71
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f4994683-7a71-491d-b14b-0a986b8ec613 # Redirect to save card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 552e3ec0-4e29-4138-873a-3058c8de918e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4dc77ff-7c96-4d98-b434-ed37c72fa8be # Matrix Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 276d4825-edef-4c4a-85d9-b1139e885c90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aef95062-e6a3-45c5-b2ef-2049189ff4f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ad55fd2-2c4e-436b-a572-d9d4bef64524 # Basic Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fd7e71a-96f2-4be9-9170-ed10f50b368a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2a4fd533-2639-4f60-8d09-671437e220e3
        userCondition: null
handle: timesheets
hasTitleField: true
name: Timesheets
section: 2fb10287-0857-4ab6-ae4e-bcce5dde9d87 # Timesheets
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
