tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 646a52b6-154e-4e2e-846b-72c6d35feadf # Timer
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0f47deaa-e798-45c3-a88b-484fed362c9c
        userCondition: null
        warning: null
        width: 100
    name: Timer
    uid: 8a5aa9b0-01fa-40f1-b8a9-a7966bbbb51b
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 5c62d201-a99d-45f2-bc77-eecf4383c50a # Timezone
        instructions: null
        label: null
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 02d67697-be25-464b-9d75-d3a368e66c77
        userCondition: null
        warning: null
        width: 100
    name: Timezone
    uid: 6b444f12-7cb1-41bd-a08b-b9a26d89dfca
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 9950af26-8378-4f58-a7ae-f7717f8870d7 # Payment method
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a0ee94d8-3e5f-44be-8c6d-e04476b15ca2
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 6f08d395-f505-46a5-b75a-f32bf4829ace # Stripe customer
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e658e524-9860-496b-976d-4c72d731fe9a
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: c9082cbb-9b75-4045-9758-066e0c93d453 # Subscription status
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c237169b-088a-427b-9931-92473eb22384
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 8f1638fd-59fe-4a3d-924c-f35248de5837 # Subscription expires
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 02d9acbb-38e8-4495-a470-a0cc2224149c
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: da63acfe-db82-4781-98a1-7fe653f511c8 # Stripe session id
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: bc599176-5361-4838-a545-bb679f2b4ab1
        userCondition: null
        warning: null
        width: 50
    name: Stripe
    uid: 45ce7292-c287-440e-8ada-e73520920ffd
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: bb86fabf-06ca-4369-94a6-298c9595fce2 # Unlimited break start
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a4fbdc4a-fe7f-4f72-8ffd-54e2c6bff923
        userCondition: null
        warning: null
        width: 100
    name: Break
    uid: 74872fa4-4b83-4dc7-9b4d-9c32261341d6
    userCondition: null
