tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 646a52b6-154e-4e2e-846b-72c6d35feadf # Timer
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 0f47deaa-e798-45c3-a88b-484fed362c9c
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: bb86fabf-06ca-4369-94a6-298c9595fce2 # Unlimited break start
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a4fbdc4a-fe7f-4f72-8ffd-54e2c6bff923
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: b0685fcd-4b89-4f1f-b2fa-c95dbf8f5691 # Hide inactive tasks
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 27d1edb3-2995-471f-80cf-ac066e3117ed
        userCondition: null
        warning: null
        width: 50
    name: Tasks
    uid: 8956e8e0-6d5e-4af1-b55a-37f8788296dc
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 5c62d201-a99d-45f2-bc77-eecf4383c50a # Timezone
        instructions: null
        label: null
        required: true
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 02d67697-be25-464b-9d75-d3a368e66c77
        userCondition: null
        warning: null
        width: 100
    name: Timezone
    uid: 6b444f12-7cb1-41bd-a08b-b9a26d89dfca
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 9950af26-8378-4f58-a7ae-f7717f8870d7 # Payment method
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: a0ee94d8-3e5f-44be-8c6d-e04476b15ca2
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: 6f08d395-f505-46a5-b75a-f32bf4829ace # Stripe customer
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: e658e524-9860-496b-976d-4c72d731fe9a
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: da63acfe-db82-4781-98a1-7fe653f511c8 # Stripe session id
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: bc599176-5361-4838-a545-bb679f2b4ab1
        userCondition: null
        warning: null
        width: 50
      -
        elementCondition: null
        fieldUid: f8cdae36-af2a-4da3-a8b6-170b7dd97716 # Last charge failed
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 877a1667-f42a-4f54-be9c-c033bb2613a7
        userCondition: null
        warning: null
        width: 50
    name: Stripe
    uid: 45ce7292-c287-440e-8ada-e73520920ffd
    userCondition: null
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: c8cf0123-4051-4f22-b94b-bbb5845a0dc8 # Charts
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c69ce87b-216e-4bb8-9000-383695367109
        userCondition: null
        warning: null
        width: 100
    name: Analytics
    uid: b5439350-6fd0-4251-af0f-63d88f038207
    userCondition: null
