columnSuffix: nqttqakk
contentColumnType: boolean
fieldGroup: fb9eba24-cb32-4bf5-8a07-ba003842b35f # Tasks
handle: archive
instructions: null
name: Archived
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
