columnSuffix: kupicvxx
contentColumnType: string(7)
fieldGroup: fb9eba24-cb32-4bf5-8a07-ba003842b35f # Tasks
handle: backgroundColor
instructions: null
name: 'Background color'
searchable: false
settings:
  defaultColor: '#ffffff'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
