columnSuffix: null
contentColumnType: string
fieldGroup: 0ba8d9d5-2692-4324-acd8-0187c46d6e82 # Common
handle: bannerImages
instructions: null
name: 'Banner Images'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:3be80663-0614-4a4d-9626-631d2bfd20bb' # Public
  defaultUploadLocationSubpath: banners
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3be80663-0614-4a4d-9626-631d2bfd20bb' # Public
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:3be80663-0614-4a4d-9626-631d2bfd20bb' # Public
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
