columnSuffix: rsotqjyk
contentColumnType: boolean
fieldGroup: 2e3e24ad-d20e-48fc-ba6a-453f1ac66748 # User
handle: cancelAtPeriodEnd
instructions: null
name: 'Cancel at period end'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
