columnSuffix: vxmozhkk
contentColumnType:
  - 'date:datetime'
  - 'tz:string'
fieldGroup: fb9eba24-cb32-4bf5-8a07-ba003842b35f # Tasks
handle: day
instructions: null
name: Day
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
