columnSuffix: null
contentColumnType: string
fieldGroup: 18ad884e-ff55-4513-8822-fb6222c76f60 # Imagery
handle: image
instructions: null
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:3be80663-0614-4a4d-9626-631d2bfd20bb' # Public
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3be80663-0614-4a4d-9626-631d2bfd20bb' # Public
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
