columnSuffix: avtcmwcc
contentColumnType: integer(10)
fieldGroup: 0ba8d9d5-2692-4324-acd8-0187c46d6e82 # Common
handle: order
instructions: null
name: Order
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
