columnSuffix: null
contentColumnType: text
fieldGroup: 0ba8d9d5-2692-4324-acd8-0187c46d6e82 # Common
handle: redactorFull
instructions: null
name: 'Redactor (full)'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Full.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
