columnSuffix: null
contentColumnType: string
fieldGroup: fb9eba24-cb32-4bf5-8a07-ba003842b35f # Tasks
handle: taskBlock
instructions: null
name: 'Task block'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:a331f307-e71c-4961-a59b-a53ecc994e1c' # Task block
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
