columnSuffix: jpxsraso
contentColumnType: string
fieldGroup: 2e3e24ad-d20e-48fc-ba6a-453f1ac66748 # User
handle: timer
instructions: null
name: Timer
searchable: false
settings:
  contentTable: '{{%matrixcontent_timer}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
