columnSuffix: null
contentColumnType: string
fieldGroup: fb9eba24-cb32-4bf5-8a07-ba003842b35f # Tasks
handle: timerTask
instructions: null
name: 'Timer task'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:35489b9b-396d-4bf5-b052-a28c816a8095' # Scheduled task
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
