columnSuffix: iiepzlkb
contentColumnType: text
fieldGroup: 2e3e24ad-d20e-48fc-ba6a-453f1ac66748 # User
handle: timezone
instructions: null
name: Timezone
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
