defaultPlacement: end
enableVersioning: true
handle: derail
name: Derail
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a9e4f78-0e55-4b7b-9e55-4fc31c721794: # Mast
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
