defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  6a9e4f78-0e55-4b7b-9e55-4fc31c721794: # Mast
    enabledByDefault: true
    hasUrls: true
    template: _entries/singles/home
    uriFormat: __home__
type: single
