defaultPlacement: end
enableVersioning: false
handle: imagery
name: Imagery
propagationMethod: all
siteSettings:
  6a9e4f78-0e55-4b7b-9e55-4fc31c721794: # Autonomy
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: imagery
type: single
