defaultPlacement: end
enableVersioning: true
handle: pageError
name: 'Page error'
propagationMethod: all
siteSettings:
  6a9e4f78-0e55-4b7b-9e55-4fc31c721794: # Mast
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
