defaultPlacement: end
enableVersioning: false
handle: task
name: Task
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a9e4f78-0e55-4b7b-9e55-4fc31c721794: # Autonomy
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 969410ba-d45b-4440-8980-07b77faf61de
type: structure
